"""empty message

Revision ID: 2d2683497556
Revises: ccc82b102b64
Create Date: 2019-10-07 22:23:43.351816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2683497556'
down_revision = 'ccc82b102b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_first_name', table_name='clients')
    op.create_index(op.f('ix_clients_first_name'), 'clients', ['first_name'], unique=False)
    op.drop_index('ix_clients_last_name', table_name='clients')
    op.create_index(op.f('ix_clients_last_name'), 'clients', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_last_name'), table_name='clients')
    op.create_index('ix_clients_last_name', 'clients', ['last_name'], unique=1)
    op.drop_index(op.f('ix_clients_first_name'), table_name='clients')
    op.create_index('ix_clients_first_name', 'clients', ['first_name'], unique=1)
    # ### end Alembic commands ###
