"""empty message

Revision ID: 9366139004c5
Revises: 
Create Date: 2020-01-30 22:57:58.635959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9366139004c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('Property_ID', sa.Integer(), nullable=False),
    sa.Column('List_Price', sa.Integer(), nullable=True),
    sa.Column('Location', sa.String(length=128), nullable=True),
    sa.Column('Trend_Link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Property_ID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=16), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_first_name'), 'clients', ['first_name'], unique=False)
    op.create_index(op.f('ix_clients_last_name'), 'clients', ['last_name'], unique=False)
    op.create_table('contracts',
    sa.Column('trans_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('Property_ID', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('day_zero', sa.DateTime(), nullable=False),
    sa.Column('deposit_first', sa.Integer(), nullable=True),
    sa.Column('deposit_second', sa.Integer(), nullable=True),
    sa.Column('BRI_day', sa.Integer(), nullable=True),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Property_ID'], ['properties.Property_ID'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('trans_id')
    )
    op.create_table('showings',
    sa.Column('showing_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('Property_ID', sa.Integer(), nullable=True),
    sa.Column('Feedback', sa.String(length=255), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Property_ID'], ['properties.Property_ID'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('showing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showings')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_clients_last_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_first_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('properties')
    # ### end Alembic commands ###
