"""empty message

Revision ID: ca233632294f
Revises: 2d2683497556
Create Date: 2019-10-08 19:46:17.911349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca233632294f'
down_revision = '2d2683497556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties__shown')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties__shown',
    sa.Column('Property_ID', sa.INTEGER(), nullable=False),
    sa.Column('List_Price', sa.INTEGER(), nullable=True),
    sa.Column('Location', sa.VARCHAR(length=128), nullable=True),
    sa.Column('Trend_Link', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Property_ID')
    )
    # ### end Alembic commands ###
